name: PELLETS
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - matplotlib-base
  - numpy
  - opencv
  - pandas
  - pillow
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
